# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger: 

- master

- develop

pool:

vmImage: 'macos-latest'

variables:

- group: <variables group name for key-alias, keystore password, key-password>

steps:

- task: Gradle@2

inputs:

workingDirectory: ''

gradleWrapperFile: 'gradlew'

gradleOptions: '-Xmx3072m'

publishJUnitResults: false

tasks: 'assemble<variantname>'

- task: AndroidSigning@3

inputs:

apkFiles: '**/*.apk'

apksignerKeystoreFile: '<key store file>'

apksignerKeystorePassword: '$(<key store password variable name>)'

apksignerKeystoreAlias: '$(<key store alias name>)'

apksignerKeyPassword: '$(<key password>)'

zipalign: false

- task: PublishBuildArtifacts@1

inputs:

PathtoPublish: 'app/build/outputs/<path to apk>'

ArtifactName: '<project name>'

publishLocation: 'Container'